# Generated by Django 5.2.7 on 2025-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cpu', 'Processor'), ('gpu', 'Graphics Card'), ('motherboard', 'Motherboard'), ('ram', 'Memory (RAM)'), ('storage', 'Storage (SSD/HDD)'), ('psu', 'Power Supply'), ('case', 'Case'), ('cooler', 'Cooling System')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compatibility', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
