# Generated by Django 5.2.7 on 2025-12-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cpu', 'Processor'), ('gpu', 'Graphics Card'), ('motherboard', 'Motherboard'), ('ram', 'Memory (RAM)'), ('storage', 'Storage (SSD/HDD)'), ('psu', 'Power Supply'), ('case', 'Case'), ('cooler', 'Cooling System')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_gpu_length', models.IntegerField()),
                ('motherboard_support', models.JSONField(default=list)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('tdp', models.IntegerField()),
                ('chipset_support', models.JSONField(default=list)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('pcie_version', models.CharField(default='4.0', max_length=10)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('ram_type', models.CharField(max_length=20)),
                ('max_ram_freq', models.IntegerField()),
                ('form_factor', models.CharField(max_length=20)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.IntegerField()),
                ('efficiency', models.CharField(blank=True, max_length=10, null=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psu', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_type', models.CharField(max_length=20)),
                ('frequency', models.IntegerField()),
                ('capacity_gb', models.IntegerField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('components', models.ManyToManyField(related_name='builds', to='components.component')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_build_name_per_user')],
            },
        ),
    ]
