# Generated by Django 5.2.7 on 2025-11-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
