# Generated by Django 5.2.7 on 2025-11-07 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_build_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_build_name_per_user'),
        ),
    ]
