# Generated by Django 5.2.7 on 2025-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_build_unique_build_name_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
